#!/bin/bash
#
# notes-up.sh
# Author: Max Mitschke
# Date: 2017-07-16

# Application Information
APP_NAME="Notes-up"
APP_FQDN="com.github.philip-scott.notes-up"
APP_ARCH="x86_64"
APP_VERSION="1.4.4"

# Settings up build environment
LATEST_DOWNLOAD_URL="https://github.com/Philip-Scott/Notes-up/archive/${APP_VERSION}.tar.gz"
wget -O "${APP_NAME}-${APP_VERSION}.tar.gz" "${LATEST_DOWNLOAD_URL}"
tar -xvf "${APP_NAME}-${APP_VERSION}.tar.gz"

BUILD_DEPS=( "cmake" "valac" "make" "squashfs-tools" "libgranite-dev" "libgee-0.8-dev" "libgtksourceview-3.0-dev" "libgtk-3-dev" "libwebkit2gtk-4.0-dev" "libsqlite3-dev" )
sudo apt install -y "${BUILD_DEPS[@]}"

# Build
cd "${APP_NAME}-${APP_VERSION}"
cmake -DCMAKE_INSTALL_PREFIX=usr/ -Dnoele=1 .
make install
cd ..

# Create AppImage
APPIMAGE="appimagetool-x86_64.AppImage"
wget -O "${APPIMAGE}" "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
chmod a+x "${APPIMAGE}"

APPIMAGE_DEPLOYQT="linuxdeployqt-continuous-x86_64.AppImage"
wget -O "${APPIMAGE_DEPLOYQT}" "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
chmod a+x ${APPIMAGE_DEPLOYQT}

mkdir -p "${APP_NAME}-${APP_ARCH}.AppDir/"
cp -r "${APP_NAME}-${APP_VERSION}/usr/" "${APP_NAME}-${APP_ARCH}.AppDir/"
#cp "${APP_NAME}-${APP_VERSION}/data/${APP_FQDN}.appdata.xml" "${APP_NAME}-${APP_ARCH}.AppDir/usr/share/metainfo/"
#cp "${APP_NAME}-${APP_VERSION}/data/${APP_FQDN}.svg" "${APP_NAME}-${APP_ARCH}.AppDir/"
#cp "${APP_NAME}-${APP_VERSION}/data/${APP_FQDN}.desktop" "${APP_NAME}-${APP_ARCH}.AppDir/"
#sed -i 's/Exec=notes-up/Exec=env GSETTING_SCHEMAS=usr\/share\/glib-2.0\/schemas\/ notes-up/g' "${APP_NAME}-${APP_ARCH}.AppDir/usr/share/applications/${APP_FQDN}.desktop"

$(pwd)/${APPIMAGE_DEPLOYQT} "${APP_NAME}-${APP_ARCH}.AppDir/usr/share/applications/${APP_FQDN}.desktop" -bundle-non-qt-libs
rm -f "${APP_NAME}-${APP_ARCH}.AppDir/AppRun"
echo '#!/bin/bash' > "${APP_NAME}-${APP_ARCH}.AppDir/AppRun"
echo 'export LD_LIBARY_PATH=$(dirname $0)/usr/lib/:${PATH}' >> "${APP_NAME}-${APP_ARCH}.AppDir/AppRun"
echo 'GSETTINGS_SCHEMA_DIR=$(dirname $0)/usr/share/glib-2.0/schemas/ $(dirname $0)/usr/bin/notes-up' >> "${APP_NAME}-${APP_ARCH}.AppDir/AppRun"
chmod a+x "${APP_NAME}-${APP_ARCH}.AppDir/AppRun"
#$(pwd)/${APPIMAGE_DEPLOYQT} "${APP_NAME}-${APP_ARCH}.AppDir/usr/share/applications/${APP_FQDN}.desktop" -appimage -always-overwrite

# Download extra binaries
apt download libpangoft2-1.0-0
dpkg -x *.deb "${APP_NAME}-${APP_ARCH}.AppDir"

$(pwd)/${APPIMAGE} "${APP_NAME}-${APP_ARCH}.AppDir"

# Cleanup
rm -rf *.tar.gz ${APPIMAGE} ${APPIMAGE_DEPLOYQT}






